name: Update data

on:
  # Daily at 02:57
  schedule:
    - cron: "57 2 * * *"
  # on demand
  workflow_dispatch:

jobs:
  update_gasvoorraad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          pip install -r requirements.txt

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}


      - name: Create report file
        run: python gasvoorraad_plot.py

      - name: Push changes
        run: |
          git config user.name 'Stef Smeets'
          git config user.email 'stefsmeets@users.noreply.github.com'
          git add chart.json
          git commit -m "Update date"
          git push
