name: Update data

on:
  # every month
  schedule:
    - cron: "30 6 5 * *"
  # on demand
  workflow_dispatch:

jobs:
  update_gasvoorraad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create report file
        run: date +%s > report.txt

      - name: Push changes
        run: |
          git config user.name 'Stef Smeets'
          git config user.email 'stefsmeets@users.noreply.github.com'
          git add report.txt
          git commit -m "Update date"
          git push
